version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "your-package-1"
      - dependency-name: "your-package-2"
    ignore:
      - dependency-name: "*"  # blocks all others EXCEPT those above
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"  # groups all security updates in one PR
