version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "rxjs"
      - dependency-name: "tslib"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
